AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  ResourcePrefix:
    Description: Resource prefix to allow testing in 1 account
    Type: String
    Default: ''
  OrchestratorName:
    Description: Resource prefix to allow testing in 1 account
    Type: String
    Default: StepFormationOrchestrator
  LogLevel:
    Description: Log Level for lambda
    Type: String
    Default: INFO
Resources:
  DeployBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${ResourcePrefix}step-formation-deploy-bucket-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  DeployBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref DeployBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadForGetObject
            Effect: Allow
            Principal: !Ref AWS::AccountId
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::${ResourcePrefix}step-formation-deploy-bucket-${AWS::AccountId}-${AWS::Region}/*"

  DeployUser:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ResourcePrefix}${OrchestratorName}Role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - states.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: !Sub ${ResourcePrefix}${OrchestratorName}Policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:DescribeLogGroups
            - logs:DescribeLogStreams
            - logs:PutLogEvents
            - logs:GetLogEvents
            - logs:FilterLogEvents
            Resource: "*"
          - Effect: Allow
            Action:
            - lambda:invoke
            - states:DeleteActivity
            - states:DeleteStateMachine
            - states:DescribeActivity
            - states:DescribeExecution
            - states:DescribeStateMachine
            - states:DescribeStateMachineForExecution
            - states:GetActivityTask
            - states:GetExecutionHistory
            - states:ListActivities
            - states:ListExecutions
            - states:ListStateMachines
            - states:ListTagsForResource
            - states:SendTaskFailure
            - states:SendTaskHeartbeat
            - states:SendTaskSuccess
            - states:StartExecution
            - states:StopExecution
            - states:TagResource
            - states:UntagResource
            - states:UpdateStateMachine
            Resource: "*"
  
  StepFunctionOrchestrator:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub ${ResourcePrefix}${OrchestratorName}StateMachine
      RoleArn: !GetAtt DeployUser.Arn
      DefinitionString: |
        {
            "Comment": "Hey",
            "StartAt": "Hello",
            "States": {
                "Hello": {
                    "Type": "Pass",
                    "Result": "Hello",
                    "Next": "World"
                },
                "World": {
                    "Type": "Pass",
                    "Result": "World",
                    "End": true
                }
            }
        }

  ExecuteCfnLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${ResourcePrefix}ExecuteCfnLambda
      Description: "Deployes cloudformation template"
      Handler: cfn_execute.handler
      Runtime: python3.6
      MemorySize: 128
      Timeout: 120
      Role: !GetAtt ExecuteCfnLambdaRole.Arn
      Environment:
        Variables:
          LOG_LEVEL: !Ref LogLevel
      # CodeUri:
      #   Bucket: !Ref DBConfigLambdaBucket
      #   Key: !Ref CfnDeployLambdaKey

  ExecuteCfnLambdaPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: 'Execute-Policy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: "*"
            Resource: "*"

  ExecuteCfnLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub ${ResourcePrefix}ExecuteCfnLambdaRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: 'allowlambda'
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
              # TODO: add only lambda to assume role
            Action: "sts:AssumeRole"
      Path: /
      ManagedPolicyArns:
        - !Ref ExecuteCfnLambdaPolicy
        - arn:aws:iam::aws:policy/service-role/AWSLambdaENIManagementAccess
